# Generated by Django 4.2.23 on 2025-07-29 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('opp_type', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField()),
                ('requirements', models.TextField()),
                ('benefits', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('app_url', models.URLField(blank=True, null=True)),
                ('application_process', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='users.employee')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('student', 'Student'), ('head', 'Head')], max_length=50),
        ),
        migrations.CreateModel(
            name='OpportunityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('on_progress', 'On progress'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='on_progress', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_applications', to='users.user')),
            ],
        ),
    ]
